### ISSUE TITLE
Current release does not compile using current Rust

### ISSUE THREAD

**Issue by alerque** [ChristophWurst/krankerl#875] opened 2021-08-19 20:50 UTC
The lockfile in the 0.13.1 release is a bit stale and making life difficult. It has an old version of the `git2` crate pinned that does not compile on the current Rust stable compiler release:

```
error[E0495]: cannot infer an appropriate lifetime due to conflicting requirements
  --> /build/.cargo/registry/src/github.com-1ecc6299db9ec823/git2-0.13.18/src/attr.rs:74:15
   |
74 |         match (self, other) {
   |               ^^^^^^^^^^^^^
   |
note: first, the lifetime cannot outlive the anonymous lifetime defined on the method body at 73:26...
  --> /build/.cargo/registry/src/github.com-1ecc6299db9ec823/git2-0.13.18/src/attr.rs:73:26
   |
73 |     fn eq(&self, other: &AttrValue<'_>) -> bool {
   |                          ^^^^^^^^^^^^^
note: ...so that the types are compatible
  --> /build/.cargo/registry/src/github.com-1ecc6299db9ec823/git2-0.13.18/src/attr.rs:74:15
   |
74 |         match (self, other) {
   |               ^^^^^^^^^^^^^
   = note: expected `(&AttrValue<'_>, &AttrValue<'_>)`
              found `(&AttrValue<'_>, &AttrValue<'_>)`
note: but, the lifetime must be valid for the lifetime `'_` as defined on the impl at 72:30...
  --> /build/.cargo/registry/src/github.com-1ecc6299db9ec823/git2-0.13.18/src/attr.rs:72:30
   |
72 | impl PartialEq for AttrValue<'_> {
   |                              ^^
note: ...so that the types are compatible
  --> /build/.cargo/registry/src/github.com-1ecc6299db9ec823/git2-0.13.18/src/attr.rs:79:16
   |
79 |             | (Self::Bytes(bytes), AttrValue::String(string)) => string.as_bytes() == *bytes,
   |                ^^^^^^^^^^^^^^^^^^
   = note: expected `AttrValue<'_>`
              found `AttrValue<'_>`

error: aborting due to previous error
```
Running `cargo update` (or not using `--locked`) seems to work so the current versions of things are probably good to go. I would suggest doing a little bump action and maybe tagging a release just so that the current stable version is buildable using current stable toolchains.

**Comment by ChristophWurst** [comment] 2021-08-23 19:01
This must have been fixed with https://github.com/ChristophWurst/krankerl/pull/873 because I can't reproduce any compilation error using Rust 1.54.0.

**Comment by alerque** [comment] 2021-08-23 19:12
I can confirm this is fixed in the *master* branch HEAD. The issue here is it is broken in the last stable release tag, which is what distro packaging uses.

You can replicate this pretty easily with Rust 1.54.0

```console
$ git checkout v0.13.1
$ git reset --hard
$ cargo build --locked --release
```

Maybe time for a quick patch release?

**Comment by ChristophWurst** [comment] 2021-08-24 07:02
Done https://github.com/ChristophWurst/krankerl/releases/tag/v0.13.2

**Closed by ChristophWurst** 2021-08-24 07:02 UTC

**Comment by ChristophWurst** [comment] 2021-08-24 07:03
Will you take care of the AUR release?
